version: '3'
services:
  presto:
    hostname: presto
    image: 'starburstdata/presto:350-e.7'
    container_name: presto
    ports:
      - ${PRESTO_UI_PORT}:8080
    volumes:
      - './presto/presto-cli-0.253-executable.jar:/usr/bin/presto'
      - './presto/minio.properties:/usr/lib/presto/etc/catalog/minio.properties'
  hadoop:
    hostname: hadoop-master
    image: 'prestodb/hive3.1-hive:5'
    container_name: hadoop-master
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - './hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml'
    networks:
      - default

networks:
  default:
    name: ${NETWORK_BACKEND}
    external: true
